server:
  port: 9000

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost/db_test
    username: test1
    password: test

    flyway:
      location: classpath:db/migration